--DAY-05 : Basic Query Using Aggregate Function.

--Question-1
--WRITE A QUERY TO DISPLAY NUMBER OF EMPLOYEES GETTING SALARY LESS THEN 2000 IN DEPTNO 10.
SELECT COUNT(*)
FROM EMP
WHERE SAL<2000 AND
      DEPTNO IN (10);

--Question-2
--WRITE TOTAL SALARY NEEDED TO PAY EMPLOYEES WORKING AS CLERK.
SELECT SUM(SAL)
FROM EMP
WHERE JOB IN 'CLERK';

--Question-3
--WRITE A QUERY TO DISPLAY AVERAGE SALARY NEEDED TO PAY ALL EMPLOYEES.
SELECT AVG(SAL)
FROM EMP

--Question-4
--WRITE A QUERY TO DISPLAY NUMBER OF EMPLOYEES HAVING 'A' AS THEIR FIRST CHARACTER.
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE 'A%';

--Question-5
--WRITE A QUERY TO DISPLAY NUMBER OF EMPLOYEES WORKING AS CLERK OR MANAGER.
SELECT COUNT(*)
FROM EMP
WHERE JOB IN ('CLERK','MANAGER');

--Question-6
--WRITE A QUERY TO DISPLAY TOTAL SALARY NEEDED TO PAY EMPLOYEES HIRED IN FEB.
SELECT SUM(SAL)
FROM EMP
WHERE HIREDATE LIKE '%FEB%';

--Question-7
--WRITE A QUERY TO DISPLAY NUMBER OF EMPLOYEES REPORTING TO 7839.
SELECT COUNT(*)
FROM EMP
WHERE MGR IN 7839;

--Question-8
--WRITE A QUERY TO DISPLAY NUMBER OF EMPLOYEES GETTING COMMISSION IN DEPTNO 30.
SELECT COUNT(*)
FROM EMP
WHERE COMM IS NOT NULL AND 
      DEPTNO IN 30;

--Question-9
--WRITE A QUERY TO DISPLAY AVG SAL, TOTAL SAL, NUMBER OF EMPLOYEES AND MAXIMUM SALARY GIVEN TO EMPLOYEES WORKING AS PRESIDENT.
SELECT AVG(SAL), SUM(SAL), COUNT(*), MAX(SAL)
FROM EMP
WHERE JOB IN 'PRESIDENT';

--Question-10
--WRITE A QUERY TO DISPLAY NUMBER OF EMPLOYEES HAVING 'A' IN THEIR NAMES.
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%A%';

--Question-11
--WRITE A QUERY TO DISPLAY NUMBER OF EMPLOYEES AND TOTAL SALARY NEEDED TO PAY THE EMPLOYEES WHO HAVE 2 CONSECUTIVE L's IN THEIR NAMES.
SELECT COUNT(*), SUM(SAL)
FROM EMP
WHERE ENAME LIKE '%LL%';

--Question-12
--WRITE A QUERY TO DISPLAY NUMBER OF DEPARTMENTS PRESENT IN EMPLOYEE TABLE.
SELECT COUNT(DISTINCT(DEPTNO)) AS Total_Departments
FROM EMP;

--Question-13
--WRITE A QUERY TO DISPLAY NUMBER OF EMPLOYEES HAVING CHARACTER 'Z' IN THEIR NAMES.
SELECT COUNT(*)
FROME EMP
WHERE ENAME LIKE '%Z%';


--Question-14
--WRITE A QUERY TO DISPLAY TOTAL SALARY GIVEN TO EMPLOYEES WORKING AS CLERK IN DEPTNO 30.
SELECT SUM(SAL) 
FROM EMP
WHERE JOB IN 'CLERK' AND DEPTNO IN 30;

--Question-15
--WRITE A QUERY TO DISPLAY MAXIMUM SALARY GIVEN TO THE EMPLOYEES WORKING AS ANALYST.
SELECT MAX(SAL)
FROM EMP
WHERE JOB IN 'ANALYST';

--Question-16
--WRITE A QUERY TO DISPLAY NUMBER OF DISTINCT SALARIES PRESENT IN EMPLOYEE TABLE.
SELECT COUNT(DISTINCT(SAL))
FROM EMP;


--Question-17
--WRITE A QUERY TO DISPLAY NUMBER OF JOBS PRESENT IN EMPLOYEE TABLE.
SELECT COUNT(DISTINCT(JOB))
FROM EMP;

--Question-18
--WRITE A QUERY TO DISPLAY AVG SALARY GIVEN TO THE CLERK.
SELECT AVG(SAL)
FROM EMP
WHERE JOB IN 'CLERK';

----Question-19
--WRITE A QUERY TO DISPLAY MINIMUM SALARY GIVEN TO THE EMPLOYEES WHO WORK IN DEPT 10 AS MANAGER OR A CLERK.
SELECT MIN(SAL)
FROM EMP
WHERE DEPTNO IN 10 AND (JOB IN ('MANAGER', 'CLERK')); 

--===========================================================================================


