--DAY-04 : Basic Query Using Special Operator

--Question-1
--LIST ALL THE EMPLOYEES WHOSE COMMISION IS NULL.
SELECT ENAME
FROM EMP
WHERE COMM IS NULL;


--Question-2
--LIST ALL THE EMPLOYEES WHO DON'T HAVE A REPORTING MANAGER.
SELECT ENAME
FROM EMP
WHERE MGR IS NULL;

--Question-3
--LIST ALL THE EMPLOYEES EXCEPT THOSE WHO ARE WORKING IN DEPT 10 AND 20.
SELECT ENAME
FROM EMP
WHERE DEPT NOT IN (10,20);

--Question-4
--LIST ALL THE SALESMAN IN IN DEPT 30.
SELECT ENAME
FROM EMP
WHERE JOB IN 'SALESMAN' AND DEPTNO IN (30);

--Question-5
--LIST ALL THE EMPLOYEES WHOSE NAME DOES NOT START WITH 'S';
SELECT ENAME
FROM EMP
WHERE ENAME NOT LIKE 'S%';

--Question-6
--LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGER IN DEPT 10.
SELECT ENAME
FROM EMP
WHERE MGR IS NOT NULL AND DEPTNO IN (10);

--Question-7
--LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL AND WORKING AS CLERK.
SELECT ENAME
FROM EMP
WHERE COMM IS NULL AND JOB IN 'CLERK';

--Question-6
--LIST ALL THE EMPLOYEES WHO DON'T HAVE A REPORTING MANAGER IN DEPTNO 10 OR 30.
SELECT ENAME
FROM EMP
WHERE MGR IN NULL AND DEPTNO IN (10,30);

--Question-6
--LIST ALL THE ANALYST IN DEPT NUMBER 20 AND HAVING SALARY GREATER THAN 2500.
SELECT ENAME
FROM EMP
WHERE JOB IN 'ANALYST' AND DEPTNO IN (20) AND SAL>2500;

--Question-7
--LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH 'M' OR 'J';
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'M%' OR ENAME LIKE 'J%';

--Question-8
--LIST ALL THE SALESMAN IN DEPT 30 WITH SAL MORE THAN 2450.
SELECT ENAME
FROM EMP
WHERE JOB IN 'SALESMAN' AND DEPTNO IN 30 AND SAL>2450;

--Question-9
--LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGER AND CLERK IN DEPT 10 AND 30 WITH A SALARY IN THE RANGE OF 1000 TO 3000.
SELECT ENAME
FROM EMP
WHERE JOB NOT IN ('MANAGER', 'CLERK') AND DEPTNO IN (10,30) AND SAL BETWEEN 1000 AND 3000.

--Question-10
--LIST ALL THE DETAILS OF EMPLOYEES WITH ANNUAL SALARY EXCEPT THOSE WHO ARE WORKING IN DEPT 30.
SELECT EMP.*, 
SAL*12 AS "ANNUAL SALARY"
FROM EMP
WHERE DEPTNO NOT IN (30);

--Question-11
--LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGER IN DEPT 10 ALONG WITH 10% HIKE IN SALARY.
SELECT ENAME , SAL+SAL*0.1 "SALARY_WITH_10%_HIKE"
FROM EMP
WHERE MGR IS NOT NULL AND DEPTNO IN (10);

--Question-12
--DISPLAY ALL THE EMPLOYEES WHO ARE JOINED AFTER YEAR 81.
SELECT ENAME
FROM EMP
WHERE HIREDATE > TO_DATE('31-DEC-1981','DD-MON-YYYY');

--Question-13
--DISPLAY ALL THE EMPLOYEES WHO ARE JOINED IN FEB.
SELECT ENAME
FROM EMP
WHERE HIREDATE LIKE '%FEB%';

--------------------------------------------------------------------------------------------


