--DAY-03 : Basic Query Using Logical Operator

--Question-1
--WRITE A QUERY TO DISPLAY OF THE EMPLOYEES WORKING AS CLERK AND EARNING LESS THAN 1500.
SELECT ENAME
FROM EMP
WHERE JOB='CLERK' AND SAL<1500;


--Question-2
--WRITE A QUERY TO DISPLAY ENAME AND HIREDATE OF THE EMPLOYEES WORKING AS MANAGER IN DEPARTMENT 30.
SELECT ENAME, HIREDATE
FROM EMP
WHERE JOB='MANAGER' AND DEPTNO=30;


--Question-3
--WRITE A QUERY TO DISPLAY DETAILS OF THE EMPLOYEE ALONG WITH ANNUAL SALARY IF THEY ARE WORKING IN DEPARTMENT 30 AS SALESMAN AND THEIR ANNUAL SALARY IS GREATER THAN 1400.
SELECT EMP.*, SAL*12 AS "ANNUAL SALARY"
FROM EMP
WHERE DEPTNO=30 AND JOB='SALESMAN' AND SAL*12>1400;


--Question-4
--WRITE A QUERY TO DISPLAY ALL THE DETAILS OF THE EMPLOYEE WORKING IN DEPARTMENT 30 OR AS ANALYST.
SELECT *
FROM EMP
WHERE DEPTNO=30 OR JOB='ANALYST';


--Question-5
--WRITE A QUERY TO DISPLAY NAMES OF THE EMPLOYEES WHOS SALARY IS LESS THAN 1100 AND THEIR, DESIGNATION IS CLERK.
SELECT ENAME
FROM EMP
WHERE SAL<1100 AND JOB='CLERK';


--Question-6
--WRITE A QUERY TO DISPLAY ENAME ,SAL, ANNUAL SALARY AND DEPTNO IF DEPTNO IS 20 AND EARNING MORE THAN 1100.
SELECT ENAME, SAL, DEPTNO, SAL*12 AS "ANNUAL SALARY"
FROM EMP
WHERE DEPTNO=20 AND SAL>1100;


--Question-7
--WRITE A QUERY TO DISPLAY EMPNO AND NAMES OF THE EMPLOYEES WORKING AS MANAGER IN DEPTNO 20.
SELECT EMPNO, ENAME
FROM EMP
WHERE JOB='MANAGER' AND DEPTNO=20;


--Question-8
--WRITE A QUERY TO DISPLAY DETAILS OF EMPLOYEES WORKING IN DEPTNO 20 OR 30.
SELECT *
FROM EMP
WHERE DEPTNO=20 OR DEPTNO=30;


--Question-9
--WRITE A QUERY TO DISPLAY DETAILS OF EMPLOYEES WORKING AS ANALYST IN DEPT 10.
SELECT *
FROM EMP
WHERE JOB='ANALYST' AND DEPTNO=10;


--Question-10
--WRITE A QUERY TO DISPLAY DETAILS OF EMPLOYEE WORKING AS PRESIDENT WITH SALARY OF 4000.
SELECT *
FROM EMP
WHERE JOB='PRESIDENT' AND SAL=4000;


--Question-11
--WRITE A QUERY TO DISPLAY ENAME AND DEPTNO, JOB OF EMPLOYEES WORKING AS CLERK IN DEPTNO 10 OR 20.
SELECT ENAME, DEPTNO, JOB
FROM EMP
WHERE JOB='CLERK' AND (DEPTNO=10 OR DEPTNO=20);


--Question-12
--WRITE A QUERY TO DISPLAY DETAILS OF EMPLOYEES WORKING AS CLERK OR MANAGER IN DEPTNO 10.
SELECT *
FROM EMP
WHERE  (JOB='CLERK' OR JOB='MANAGER') AND DEPTNO=10;


--Question-13
--WRITE A QUERY TO DISPLAY NAMES OF EMPLOYEES WORKING IN DEPTNO 10,20,30,40.
SELECT ENAME
FROM EMP
WHERE DEPTNO=10 OR DEPTNO=20 OR DEPTNO=30 OR DEPTNO=40;


--Question-14
--WRITE A QUERY TO DISPLAY DETAILS OF EMPLOYEES WITH EMPNO 7902, 7839.
SELECT *
FROM EMP
WHERE EMPNO=7902 OR EMPNO=7839;


--Question-15
--WRITE A QUERY TO DISPLAY DETAILS OF EMPLOYEES WORKING AS MANAGER OR SALESMAN OR CLERK.
SELECT *
FROM EMP
WHERE JOB='MANAGER' OR JOB='SALESMAN' OR JOB='CLERK';


--Question-16
--WRITE A QUERY TO DISPLAY NAMES OF EMPLOYEES HIRED AFTER 81 AND BEFORE 87.
SELECT ENAME
FROM EMP
WHERE HIREDATE>'31-DEC-81' AND HIREDATE<'01-JAN-87';


--Question-17
--WRITE A QUERY TO DISPLAY DETAILS OF EMPLOYEES EARNING MORE THAN 1250 BUT LESS THAN 3000.
SELECT *
FROM EMP
WHERE SAL>1250 AND SAL<3000;


--Question-18
--WRITE A QUERY TO DISPLAY NAMES OF EMPLOYEES HIRED AFTER 81 INTO DEPT 10 OR 30.
SELECT ENAME
FROM EMP
WHERE HIREDATE>'31-DEC-81' AND (DEPTNO=10 OR DEPTNO=30);

--Question-19
--WRITE A QUERY TO DISPLAY NAMES OF EMPLOYEES ALONG WITH ANNUAL SALARY FOR THE EMPLOYEES WORKING AS MANAGER OR CLERK INTO DEPT 10 OR 30.
SELECT ENAME, SAL*12 AS "ANNUAL SALARY"
FROM EMP
WHERE (JOB='MANAGER' OR JOB='CLERK') AND (DEPTNO=10 OR DEPTNO=30);

--Question-20
--WRITE A QUERY TO DISPLAY ALL THE DETAILS ALONG WITH ANNUAL SALARY IF SAL IS BETWEEN 1000 AND 4000 AND ANNUAL SALARY IS MORE THAN 15000.
SELECT EMP.*, SAL*12 AS "ANNUAL SALARY"
FROM EMP
WHERE SAL>=1000 AND SAL<=4000 AND SAL*12>15000;













 




