-- Day-01: Basic Select Query
-- ORACLE SYNTAX IS USED

-- QUESTION 1
-- DISPLAY NAME OF THE EMPLOYEE ALONG WITH THEIR ANNUAL SALARY.
SELECT ENAME, SAL*12 AS "ANNUAL_SALARY"
FROM EMP;

-- QUESTION 2
-- DISPLAY EMPLOYEE NAME AND JOB WITH THEIR HALF-YEAR SALARY.
SELECT ENAME,
       JOB, 
       SAL*6 AS "HALF_YEAR_SALARY"
FROM EMP;

-- QUESTION 3
-- DISPLAY ALL DETAILS OF EMPLOYEES ALONG WITH AN ANNUAL BONUS OF 2000.
SELECT EMP.*, 
       (SAL*12)+2000 AS "SALARY_WITH_ANNUAL_BONUS_2000"
FROM EMP;

-- QUESTION 4
-- DISPLAY NAME AND SALARY WITH A HIKE OF 10%.
SELECT ENAME, 
       SAL + (SAL*0.1) AS "SALARY_HIKE_10_PERCENT"
FROM EMP;

-- QUESTION 5
-- DISPLAY NAME AND SALARY AFTER DEDUCTING 25%.
SELECT ENAME, 
       SAL, 
       SAL - (SAL*0.25) AS "SALARY_AFTER_25_PERCENT_DEDUCTION"
FROM EMP;

-- QUESTION 6
-- DISPLAY TOTAL SALARY GIVEN TO EACH EMPLOYEE (SALARY + COMMISSION).
SELECT ENAME, 
       SAL + NVL(COMMISSION,0) AS "TOTAL_SALARY"
FROM EMP;

-- QUESTION 7
-- DISPLAY NAME AND DESIGNATION ALONG WITH 100 RUPEE PENALTY IN SALARY.
SELECT ENAME, 
       JOB, 
       SAL - 100 AS "SALARY_WITH_100_PENALTY"
FROM EMP;
